### ISSUE TITLE
Look into the Influx PodDisruptionBudget

### ISSUE THREAD

**Issue by amrc-benmorrow** [AMRC-FactoryPlus/amrc-connectivity-stack#104]
As we currently deploy it, InfluxDB has a StatefulSet running 1 replica, and a PodDisruptionBudget with minAvailability of 1. This means the influx pod will never willingly drain, and is causing operational problems.

We need to work out how to fix this.
* Do we just remove the PDB? How do we do that?
* If we wanted 2 replicas how does the storage work?

**Comment by AlexGodbehere** [comment]
#105

**Comment by AlexGodbehere** [comment]
Fixed in `v2.4.7`
