### ISSUE TITLE
Allow to select a separate data source for each metric

### ISSUE THREAD

**Issue by grigals** [AMRC-FactoryPlus/amrc-connectivity-stack#221]
Allow each schema metric to be assigned a metric from a different source (MQTT/REST/etc)

**Comment by amrc-benmorrow** [comment]
I don't think this is a good idea. Pulling all the metrics for a Device from a single Connection allows the Device to DBIRTH/DDEATH when the connection goes up or down. Pulling from multiple connections would confuse this situation.

Cases where this seems to be desirable should be handled with Links.
