### ISSUE TITLE
Move edge-helm-charts repository into monorepo

### ISSUE THREAD

**Issue by AlexGodbehere** [AMRC-FactoryPlus/amrc-connectivity-stack#286]
Currently the release process for ACS is fragmented and convoluted. It involves changing the source of multiple repositories and cutting a new release in both `amrc-connectivity-stack` and `edge-helm-charts`. Instead, move the contents of the `edge-helm-charts` repo to the `amrc-connectivity-stack` monorepo and build an image that stores the charts and includes a worker that patches the internal Git repository when deployed. Additionally, using templated placeholders for version numbers should allow the release process to update them without having to manually edit the source before release. The end goal here is to have a process for releasing that consists of simply cutting a new `amrc-connectivity-stack` release.

- [x] Move `edge-helm-charts` contents to `amrc-connectivity-stack`
- [x] Create worker to patch internal Git repository
- [x] Create Dockerfile
- [x] Move current `service-setup` to first `initContainer`
- [x] Add `initContainer` to `service-setup` to run on install that uses the new above image
- [x] Remove the `pull:` config from the `Edge Helm charts` Git repository in new and existing installations
- [ ] Replace hardcoded version numbers with `$FP_VER$`
- [ ] Update Github Action to replace the placeholders across specified files with the actual build tag before building the images.

**Comment by amrc-benmorrow** [comment]
The linked PR does **not** implement the last two tick-boxes above.

**Comment by amrc-benmorrow** [comment]
The final two tickboxes have moved to #318 .
