### ISSUE TITLE
Allow all containers to be pulled from private registries

### ISSUE THREAD

**Issue by derme302** [AMRC-FactoryPlus/amrc-connectivity-stack#89]
Currently most of the containers in the stack can be overridden to be pulled from a private registry, except for `kubegres-controller-manager`.

It would be great if the registry address for both `kubegres-controller-manager` and `manager` were exposed in the `values.yaml`. Along with this it would be great to have `imagePullSecrets` exposed as these exist in a different namespace to the rest of the containers in the stack.

**Comment by amrc-benmorrow** [comment]
I'd be interested to know what your use case is here... we are currently looking into running ACS on edge systems isolated from the Internet, and we have had success using [Harbor](https://goharbor.io/) as a pull-through cache along with using k3s' [private registries configuration](https://docs.k3s.io/installation/private-registry) to configure machines to pull images through the cache. But obviously this requires some part of the network has Internet access.

**Comment by derme302** [comment]
The use case is a factory environment with no internet connection. Our images are currently in a private registry and require authentication to retrieve. 

If we wanted to remove the need to authenticate we'd need to setup another registry with just the Factory+ containers. K3's private registry configuration would work but we don't have the option to make modifications to the cluster at this point.

**Comment by amrc-benmorrow** [comment]
I believe this is now resolved with #98, #100, #113 and #114. If there are still issues please feel free to reopen.

**Comment by derme302** [comment]
Awesome, thanks @amrc-benmorrow!
